from flask import Flask, request, jsonify, send_from_directory
from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.shapes import MSO_AUTO_SHAPE_TYPE
import os
import uuid

app = Flask(__name__)

OUTPUT_FOLDER = "generated_ppts"
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

# =========================
# THEME COLORS
# =========================

TITLE_COLOR = RGBColor(0, 120, 212)
ACCENT_COLOR = RGBColor(0, 84, 159)
TEXT_COLOR = RGBColor(51, 51, 51)
LIGHT_BG = RGBColor(245, 247, 250)
WHITE = RGBColor(255, 255, 255)

# =========================
# HOME
# =========================

@app.route("/")
def home():
    return "PPT Generator Running"


# =========================
# PPT GENERATOR
# =========================

@app.route("/createppt", methods=["POST"])
def create_ppt():

    data = request.get_json()

    title = data.get(
        "presentationTitle",
        "Presentation"
    )

    slides = data.get("slides", [])

    # prevent overcrowding
    slides = slides[:10]

    prs = Presentation()

    # ====================================
    # TITLE SLIDE
    # ====================================

    title_slide = prs.slides.add_slide(
        prs.slide_layouts[0]
    )

    title_shape = title_slide.shapes.title

    title_shape.text = title

    title_para = title_shape.text_frame.paragraphs[0]

    title_para.font.size = Pt(34)
    title_para.font.bold = True
    title_para.font.color.rgb = TITLE_COLOR

    if len(title_slide.placeholders) > 1:

        subtitle = title_slide.placeholders[1]

        subtitle.text = (
            "AI Generated Executive Presentation\n"
            "Powered by Custom Tools Test V3"
        )

        subtitle_para = subtitle.text_frame.paragraphs[0]

        subtitle_para.font.size = Pt(18)
        subtitle_para.font.color.rgb = TEXT_COLOR

    # ====================================
    # CONTENT SLIDES
    # ====================================

    for s in slides:

        slide = prs.slides.add_slide(
            prs.slide_layouts[6]
        )

        # --------------------------------
        # HEADER BAR
        # --------------------------------

        header = slide.shapes.add_shape(
            MSO_AUTO_SHAPE_TYPE.RECTANGLE,
            0,
            0,
            prs.slide_width,
            Inches(0.6)
        )

        header.fill.solid()
        header.fill.fore_color.rgb = ACCENT_COLOR

        header.line.color.rgb = ACCENT_COLOR

        # --------------------------------
        # TITLE
        # --------------------------------

        title_box = slide.shapes.add_textbox(
            Inches(0.4),
            Inches(0.15),
            Inches(8),
            Inches(0.5)
        )

        title_frame = title_box.text_frame

        title_frame.text = s.get(
            "title",
            "Slide Title"
        )

        title_para = title_frame.paragraphs[0]

        title_para.font.size = Pt(24)
        title_para.font.bold = True
        title_para.font.color.rgb = WHITE

        # --------------------------------
        # CONTENT BOX
        # --------------------------------

        content_card = slide.shapes.add_shape(
            MSO_AUTO_SHAPE_TYPE.ROUNDED_RECTANGLE,
            Inches(0.4),
            Inches(1.0),
            Inches(8.7),
            Inches(4.2)
        )

        content_card.fill.solid()
        content_card.fill.fore_color.rgb = LIGHT_BG

        content_card.line.color.rgb = RGBColor(
            220,
            220,
            220
        )

        # --------------------------------
        # BULLET CONTENT
        # --------------------------------

        content_box = slide.shapes.add_textbox(
            Inches(0.7),
            Inches(1.2),
            Inches(8.0),
            Inches(3.8)
        )

        tf = content_box.text_frame

        tf.clear()

        bullets = s.get("content", [])

        bullets = bullets[:6]

        for idx, bullet in enumerate(bullets):

            if idx == 0:
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()

            p.text = f"✓ {bullet}"

            p.font.size = Pt(20)

            p.font.color.rgb = TEXT_COLOR

            p.level = 0

        # --------------------------------
        # FOOTER
        # --------------------------------

        footer_box = slide.shapes.add_textbox(
            Inches(0.5),
            Inches(6.7),
            Inches(3),
            Inches(0.3)
        )

        footer_tf = footer_box.text_frame

        footer_tf.text = (
            "Generated by Custom Tools Test V3"
        )

        footer_tf.paragraphs[0].font.size = Pt(10)

        footer_tf.paragraphs[0].font.color.rgb = RGBColor(
            120,
            120,
            120
        )

    # ====================================
    # SAVE PPT
    # ====================================

    filename = f"{uuid.uuid4()}.pptx"

    filepath = os.path.join(
        OUTPUT_FOLDER,
        filename
    )

    prs.save(filepath)

    return jsonify({
        "status": "success",
        "fileName": filename,
        "downloadUrl": (
            request.url_root
            + "download/"
            + filename
        )
    })


# =========================
# DOWNLOAD PPT
# =========================

@app.route("/download/<filename>")
def download(filename):

    return send_from_directory(
        OUTPUT_FOLDER,
        filename,
        as_attachment=True
    )


# =========================
# MAIN
# =========================

if __name__ == "__main__":
    app.run()
