from flask import Flask, request, jsonify, send_from_directory
from pptx import Presentation
from pptx.util import Pt
import os
import uuid

app = Flask(__name__)

OUTPUT_FOLDER = "generated_ppts"
os.makedirs(OUTPUT_FOLDER, exist_ok=True)

@app.route("/")
def home():
    return "PPT Generator Running"

@app.route("/createppt", methods=["POST"])
def create_ppt():

    data = request.get_json()

    title = data.get("presentationTitle","Presentation")

    slides = data.get("slides",[])

    prs = Presentation()

    title_slide = prs.slides.add_slide(
        prs.slide_layouts[0]
    )

    title_slide.shapes.title.text = title

    if len(title_slide.placeholders) > 1:
        title_slide.placeholders[1].text = "Generated by Custom Tools Test V3"

    for s in slides:

        slide = prs.slides.add_slide(
            prs.slide_layouts[1]
        )

        slide.shapes.title.text = s["title"]

        tf = slide.placeholders[1].text_frame

        tf.clear()

        for i, bullet in enumerate(s["content"]):

            if i == 0:
                p = tf.paragraphs[0]
            else:
                p = tf.add_paragraph()

            p.text = bullet
            p.font.size = Pt(18)

    filename = f"{uuid.uuid4()}.pptx"

    filepath = os.path.join(
        OUTPUT_FOLDER,
        filename
    )

    prs.save(filepath)

    return jsonify({
        "status":"success",
        "fileName":filename,
        "downloadUrl":request.url_root +
                      "download/" +
                      filename
    })

@app.route("/download/<filename>")
def download(filename):

    return send_from_directory(
        OUTPUT_FOLDER,
        filename,
        as_attachment=True
    )

if __name__ == "__main__":
    app.run()
